### PR TITLE
Allow underscores in env variables

### PR DESCRIPTION
**Pull request by maartenjanvangool**
I wonder what you think. We're running into the issue that gitalb ci does not allow dots in environment variables, so I'm unable to set properties on the project level. By replacing underscores with dots this problem will be solved. I am told this is in parallel with how spring boot handles properties. So this would be a nice addition.

### CODE REVIEW

**Comment by maartenjanvangool** [comment]
Fixed the formatting, please review? It is starting to feel like I have to make a release of my own... Got another PR coming...

**Comment by HardNorth** [comment]
> Fixed the formatting, please review? It is starting to feel like I have to make a release of my own... Got another PR coming...

Well, nobody can stop you of doing that. But to be honest I'm getting from 120 to 320 GitHub notifications every day including weekends. It already went beyond my abilities to track everything. So if you want your requests to be more visible please join our [slack chat](https://reportportal-slack-auto.herokuapp.com/) and ping me and other folks directly.

**Comment by orangebeard-io** [comment]
@HardNorth I will slack you next time. Thanks for merging my PR's :-).

**Comment by maartenjanvangool** [comment]
@HardNorth I will slack you next time. Thanks for merging my PR's :-).

**Pull request merged**
